/*
  Warnings:

  - The values [DOCTOR_CREATE,DOCTOR_READ,DOCTOR_UPDATE,DOCTOR_DELETE,SETTINGS_MANAGE] on the enum `PermissionName` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "PermissionName_new" AS ENUM ('USER_CREATE', 'USER_READ', 'USER_UPDATE', 'USER_DELETE', 'PATIENT_CREATE', 'PATIENT_READ', 'PATIENT_UPDATE', 'PATIENT_DELETE', 'MEDIC_CREATE', 'MEDIC_READ', 'MEDIC_UPDATE', 'MEDIC_DELETE', 'APPOINTMENT_CREATE', 'APPOINTMENT_READ', 'APPOINTMENT_UPDATE', 'APPOINTMENT_DELETE', 'RESCHEDULE_CREATE', 'RESCHEDULE_READ', 'RESCHEDULE_UPDATE', 'RESCHEDULE_DELETE', 'RESCHEDULE_APPROVE', 'RESCHEDULE_REJECT', 'CONSULTATION_CREATE', 'CONSULTATION_READ', 'CONSULTATION_UPDATE', 'CONSULTATION_DELETE', 'ROLE_CREATE', 'ROLE_READ', 'ROLE_UPDATE', 'ROLE_DELETE', 'PERMISSION_CREATE', 'PERMISSION_READ', 'PERMISSION_UPDATE', 'PERMISSION_DELETE', 'ADMIN_ACCESS', 'SYSTEM_SETTINGS', 'USER_ROLE_ASSIGN');
ALTER TYPE "PermissionName" RENAME TO "PermissionName_old";
ALTER TYPE "PermissionName_new" RENAME TO "PermissionName";
DROP TYPE "PermissionName_old";
COMMIT;
