import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const examCatalogData = [
  // ========================================
  // HEMATOLOGÍA
  // ========================================
  {
    category: 'HEMATOLOGÍA',
    examName: 'Hemoglobina',
    measurementUnit: 'g/dL',
    referenceMin: 12.0,
    referenceMax: 16.0,
    dataType: 'numerico',
    normalRange: '12-16 g/dL',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Hematocrito',
    measurementUnit: '%',
    referenceMin: 36.0,
    referenceMax: 46.0,
    dataType: 'numerico',
    normalRange: '36-46%',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Hematies',
    measurementUnit: 'x mm3',
    referenceMin: 4.0,
    referenceMax: 5.5,
    dataType: 'numerico',
    normalRange: '4.0-5.5 x 10^6/mm3',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'VCM',
    measurementUnit: 'fL',
    referenceMin: 80.0,
    referenceMax: 100.0,
    dataType: 'numerico',
    normalRange: '80-100 fL',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'HCM',
    measurementUnit: 'pg',
    referenceMin: 27.0,
    referenceMax: 32.0,
    dataType: 'numerico',
    normalRange: '27-32 pg',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'CHCM',
    measurementUnit: 'g/dL',
    referenceMin: 32.0,
    referenceMax: 36.0,
    dataType: 'numerico',
    normalRange: '32-36 g/dL',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Leucocitos',
    measurementUnit: 'x mm3',
    referenceMin: 4.0,
    referenceMax: 11.0,
    dataType: 'numerico',
    normalRange: '4,000-11,000/mm3',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Segmentados',
    measurementUnit: '%',
    referenceMin: 40.0,
    referenceMax: 70.0,
    dataType: 'numerico',
    normalRange: '40-70%',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Linfocitos',
    measurementUnit: '%',
    referenceMin: 20.0,
    referenceMax: 40.0,
    dataType: 'numerico',
    normalRange: '20-40%',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Eosinófilos',
    measurementUnit: '%',
    referenceMin: 1.0,
    referenceMax: 4.0,
    dataType: 'numerico',
    normalRange: '1-4%',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Monocitos',
    measurementUnit: '%',
    referenceMin: 2.0,
    referenceMax: 8.0,
    dataType: 'numerico',
    normalRange: '2-8%',
  },
  {
    category: 'HEMATOLOGÍA',
    examName: 'Plaquetas',
    measurementUnit: 'x mm3',
    referenceMin: 150.0,
    referenceMax: 450.0,
    dataType: 'numerico',
    normalRange: '150,000-450,000/mm3',
  },

  // ========================================
  // QUÍMICA Y LÍPIDOS
  // ========================================
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'Creatinina',
    measurementUnit: 'mg/dL',
    referenceMin: 0.6,
    referenceMax: 1.2,
    dataType: 'numerico',
    normalRange: '0.6-1.2 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'Urea',
    measurementUnit: 'mg/dL',
    referenceMin: 10.0,
    referenceMax: 50.0,
    dataType: 'numerico',
    normalRange: '10-50 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'Ácido úrico',
    measurementUnit: 'mg/dL',
    referenceMin: 3.0,
    referenceMax: 7.0,
    dataType: 'numerico',
    normalRange: '3.0-7.0 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'Colesterol total',
    measurementUnit: 'mg/dL',
    referenceMin: 0.0,
    referenceMax: 200.0,
    dataType: 'numerico',
    normalRange: '<200 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'Triglicéridos',
    measurementUnit: 'mg/dL',
    referenceMin: 0.0,
    referenceMax: 150.0,
    dataType: 'numerico',
    normalRange: '<150 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'HDL',
    measurementUnit: 'mg/dL',
    referenceMin: 40.0,
    referenceMax: 60.0,
    dataType: 'numerico',
    normalRange: '>40 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'LDL',
    measurementUnit: 'mg/dL',
    referenceMin: 0.0,
    referenceMax: 100.0,
    dataType: 'numerico',
    normalRange: '<100 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'VLDL',
    measurementUnit: 'mg/dL',
    referenceMin: 0.0,
    referenceMax: 30.0,
    dataType: 'numerico',
    normalRange: '<30 mg/dL',
  },
  {
    category: 'QUÍMICA Y LÍPIDOS',
    examName: 'Colesterol No HDL',
    measurementUnit: 'mg/dL',
    referenceMin: 0.0,
    referenceMax: 130.0,
    dataType: 'numerico',
    normalRange: '<130 mg/dL',
  },

  // ========================================
  // PROTEINAS
  // ========================================
  {
    category: 'PROTEINAS',
    examName: 'Proteínas Totales',
    measurementUnit: 'g/dL',
    referenceMin: 6.0,
    referenceMax: 8.3,
    dataType: 'numerico',
    normalRange: '6.0-8.3 g/dL',
  },
  {
    category: 'PROTEINAS',
    examName: 'Albúmina',
    measurementUnit: 'g/dL',
    referenceMin: 3.5,
    referenceMax: 5.0,
    dataType: 'numerico',
    normalRange: '3.5-5.0 g/dL',
  },
  {
    category: 'PROTEINAS',
    examName: 'Globulinas',
    measurementUnit: 'g/dL',
    referenceMin: 2.0,
    referenceMax: 3.5,
    dataType: 'numerico',
    normalRange: '2.0-3.5 g/dL',
  },

  // ========================================
  // ENDOCRINO-METABÓLICO - INSULINO-RESISTENCIA
  // ========================================
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'T3 Libre',
    measurementUnit: 'pg/mL',
    referenceMin: 2.0,
    referenceMax: 4.4,
    dataType: 'numerico',
    normalRange: '2.0-4.4 pg/mL',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'T4 Libre',
    measurementUnit: 'ng/dL',
    referenceMin: 0.8,
    referenceMax: 1.8,
    dataType: 'numerico',
    normalRange: '0.8-1.8 ng/dL',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'TSH',
    measurementUnit: 'µUI/mL',
    referenceMin: 0.4,
    referenceMax: 4.0,
    dataType: 'numerico',
    normalRange: '0.4-4.0 µUI/mL',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Insulinemia basal',
    measurementUnit: 'µU/mL',
    referenceMin: 2.0,
    referenceMax: 25.0,
    dataType: 'numerico',
    normalRange: '2-25 µU/mL',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Insulinemia 60 min',
    measurementUnit: 'µU/mL',
    referenceMin: null,
    referenceMax: null,
    dataType: 'numerico',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Insulinemia 120 min',
    measurementUnit: 'µU/mL',
    referenceMin: null,
    referenceMax: null,
    dataType: 'numerico',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Glicemia basal',
    measurementUnit: 'mg/dL',
    referenceMin: 70.0,
    referenceMax: 100.0,
    dataType: 'numerico',
    normalRange: '70-100 mg/dL',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Glicemia 60 min',
    measurementUnit: 'mg/dL',
    referenceMin: null,
    referenceMax: 140.0,
    dataType: 'numerico',
    normalRange: '<140 mg/dL',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Glicemia 120 min',
    measurementUnit: 'mg/dL',
    referenceMin: null,
    referenceMax: 140.0,
    dataType: 'numerico',
    normalRange: '<140 mg/dL',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Hb glicosilada',
    measurementUnit: '%',
    referenceMin: 4.0,
    referenceMax: 5.6,
    dataType: 'numerico',
    normalRange: '4.0-5.6%',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'Trig/HDL',
    measurementUnit: 'ratio',
    referenceMin: 0.0,
    referenceMax: 3.0,
    dataType: 'numerico',
    normalRange: '<3.0',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'HOMA-IR',
    measurementUnit: 'índice',
    referenceMin: 0.0,
    referenceMax: 2.5,
    dataType: 'numerico',
    normalRange: '<2.5',
  },
  {
    category: 'ENDOCRINO-METABÓLICO',
    examName: 'HOMA B Cell',
    measurementUnit: '%',
    referenceMin: null,
    referenceMax: null,
    dataType: 'numerico',
  },

  // ========================================
  // HEPÁTICOS
  // ========================================
  {
    category: 'HEPÁTICOS',
    examName: 'TGO',
    measurementUnit: 'U/L',
    referenceMin: 0.0,
    referenceMax: 40.0,
    dataType: 'numerico',
    normalRange: '<40 U/L',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'TGP',
    measurementUnit: 'U/L',
    referenceMin: 0.0,
    referenceMax: 40.0,
    dataType: 'numerico',
    normalRange: '<40 U/L',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'PCR',
    measurementUnit: 'mg/L',
    referenceMin: 0.0,
    referenceMax: 5.0,
    dataType: 'numerico',
    normalRange: '<5 mg/L',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'Bilirrubina total',
    measurementUnit: 'mg/dL',
    referenceMin: 0.1,
    referenceMax: 1.2,
    dataType: 'numerico',
    normalRange: '0.1-1.2 mg/dL',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'Bilirrubina directa',
    measurementUnit: 'mg/dL',
    referenceMin: 0.0,
    referenceMax: 0.3,
    dataType: 'numerico',
    normalRange: '<0.3 mg/dL',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'Bilirrubina indirecta',
    measurementUnit: 'mg/dL',
    referenceMin: 0.1,
    referenceMax: 0.9,
    dataType: 'numerico',
    normalRange: '0.1-0.9 mg/dL',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'Fosfatasa alcalina ALP',
    measurementUnit: 'U/L',
    referenceMin: 30.0,
    referenceMax: 120.0,
    dataType: 'numerico',
    normalRange: '30-120 U/L',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'Gammaglutamiltranspeptidasa',
    measurementUnit: 'U/L',
    referenceMin: 0.0,
    referenceMax: 60.0,
    dataType: 'numerico',
    normalRange: '<60 U/L',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'TP paciente',
    measurementUnit: 'seg',
    referenceMin: 11.0,
    referenceMax: 13.5,
    dataType: 'numerico',
    normalRange: '11-13.5 seg',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'TP control',
    measurementUnit: 'seg',
    referenceMin: null,
    referenceMax: null,
    dataType: 'numerico',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'INR',
    measurementUnit: 'ratio',
    referenceMin: 0.8,
    referenceMax: 1.2,
    dataType: 'numerico',
    normalRange: '0.8-1.2',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'TPT paciente',
    measurementUnit: 'seg',
    referenceMin: 25.0,
    referenceMax: 35.0,
    dataType: 'numerico',
    normalRange: '25-35 seg',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'TPT control',
    measurementUnit: 'seg',
    referenceMin: null,
    referenceMax: null,
    dataType: 'numerico',
  },
  {
    category: 'HEPÁTICOS',
    examName: 'Relación TPT',
    measurementUnit: 'ratio',
    referenceMin: null,
    referenceMax: null,
    dataType: 'numerico',
  },

  // ========================================
  // ELECTROLITOS
  // ========================================
  {
    category: 'ELECTROLITOS',
    examName: 'Calcio',
    measurementUnit: 'mg/dL',
    referenceMin: 8.5,
    referenceMax: 10.5,
    dataType: 'numerico',
    normalRange: '8.5-10.5 mg/dL',
  },
  {
    category: 'ELECTROLITOS',
    examName: 'Magnesio',
    measurementUnit: 'mg/dL',
    referenceMin: 1.7,
    referenceMax: 2.2,
    dataType: 'numerico',
    normalRange: '1.7-2.2 mg/dL',
  },
  {
    category: 'ELECTROLITOS',
    examName: 'Fósforo',
    measurementUnit: 'mg/dL',
    referenceMin: 2.5,
    referenceMax: 4.5,
    dataType: 'numerico',
    normalRange: '2.5-4.5 mg/dL',
  },
  {
    category: 'ELECTROLITOS',
    examName: 'Sodio',
    measurementUnit: 'mmol/L',
    referenceMin: 135.0,
    referenceMax: 145.0,
    dataType: 'numerico',
    normalRange: '135-145 mmol/L',
  },
  {
    category: 'ELECTROLITOS',
    examName: 'Potasio',
    measurementUnit: 'mmol/L',
    referenceMin: 3.5,
    referenceMax: 5.0,
    dataType: 'numerico',
    normalRange: '3.5-5.0 mmol/L',
  },
  {
    category: 'ELECTROLITOS',
    examName: 'Cloro',
    measurementUnit: 'mmol/L',
    referenceMin: 98.0,
    referenceMax: 107.0,
    dataType: 'numerico',
    normalRange: '98-107 mmol/L',
  },

  // Continuaré con el resto de categorías en la siguiente parte...
];

export async function seedExamCatalog() {
  console.log('Seeding exam catalog...');

  for (const exam of examCatalogData) {
    await prisma.examCatalog.upsert({
      where: {
        category_examName: {
          category: exam.category,
          examName: exam.examName,
        },
      },
      update: exam,
      create: exam,
    });
  }

  console.log(`✅ Seeded ${examCatalogData.length} exams`);
}
